### Obtencion de todos los productos
GET http://localhost:1234/productos/

### Obtencion de todos los usuarios
GET http://localhost:1234/usuarios/

### Obtención de un producto específico

GET http://localhost:1234/productos/3/

### Obtención del precio de un producto específico

GET http://localhost:1234/productos/3/precio

### Obtención del nombre de un producto específico

GET http://localhost:1234/productos/3/nombre

### Obtención del stock de productos

GET http://localhost:1234/stock

### Obtención de un usuario específico

GET http://localhost:1234/usuarios/3/

### Obtención del telefono de un usuario específico

GET http://localhost:1234/usuarios/5/telefono

### Obtención del nombre de un usuario específico

GET http://localhost:1234/usuarios/5/nombre

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:1234/productos
Content-Type: application/json

{
    "id": 11,
    "nombre": "Mixer multiuso ACME",
    "tipo": "Electrodoméstico de cocina",
    "precio": 150.15
}

### Agregado de un usuario nuevo, el body lleva el json con el objeto
POST http://localhost:1234/usuarios
Content-Type: application/json

{
        "id": 11,
        "nombre": "Mauro Quinteros",
        "edad": 19,
        "email": "RoMau23@hotmail.com",
        "telefono": "+54 261-657-9225"
 }

### Actualización de un producto, el body lleva solo el atributo a modificar

PATCH http://localhost:1234/productos/10
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

### Actualización de un usuario, el body lleva solo el atributo a modificar

PATCH http://localhost:1234/usuarios/10
Content-Type: application/json

{
    "nombre": "Roberto Quintana XD"
}

### Borrado de un producto
DELETE http://localhost:1234/productos/8

### Borrado de un usuario
DELETE http://localhost:1234/usuarios/8
