### Obtencion de todos los productos
GET http://localhost:1234/productos/

### Obtencion de todos los usuarios
GET http://localhost:1234/usuarios/

### Obtención de un producto específico

GET http://localhost:1234/productos/3/

### Obtención del precio de un producto específico

GET http://localhost:1234/productos/3/precio

### Obtención del nombre de un producto específico

GET http://localhost:1234/productos/3/nombre

### Obtención del stock de productos

GET http://localhost:1234/stock

### Obtención de un usuario específico

GET http://localhost:1234/usuarios/3/

### Obtención del telefono de un usuario específico

GET http://localhost:1234/usuarios/5/dni

### Obtención del nombre de un usuario específico

GET http://localhost:1234/usuarios/5/nombre

### Agregado de un producto nuevo, el body lleva el json con el objeto
POST http://localhost:1234/productos
Content-Type: application/json

{
    "id": 8,
    "nombre": "Mixer multiuso ACME",
    "descripcion": "Electrodoméstico de cocina",
    "stock": 150,
    "categoria": "Electrodomestico",
    "proveedor": "Will Tech",
    "precio": 5000
}

### Agregado de un usuario nuevo, el body lleva el json con el objeto
POST http://localhost:1234/usuarios
Content-Type: application/json

{
        "id": 8,
        "dni": "45718410",
        "nombre": "Mauro",
        "apellido": "Quinteros",
        "email": "RoMau23@hotmail.com",
        "contraseña": "XD"
 }

### Actualización de un producto, el body lleva solo el atributo a modificar

PATCH http://localhost:1234/productos/8
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

### Actualización de un usuario, el body lleva solo el atributo a modificar

PATCH http://localhost:1234/usuarios/8
Content-Type: application/json

{
    "nombre": "Roberto"
}

### Borrado de un producto
DELETE http://localhost:1234/productos/8

### Borrado de un usuario
DELETE http://localhost:1234/usuarios/8
